version: '3'

services:

  mydb:
    image: library/mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mydb
    env_file:
      - .env
    ports:
      - 8080:8080